[tools]
fd = "latest"
fzf = "latest"
go = "latest"
neovim = "0.11"
node = "24"
ripgrep = "latest"
rust = "latest"
"cargo:tlrc" = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
"pipx:ipython" = { version = "9", uvx_args = "--with catppuccin" }
