import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[font]
size = 16.0
offset = { x = 1, y = 1 }

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[bell]
duration = 400
color = "#5c5f77"

[cursor]
style.blinking = "Never"

[scrolling]
history = 100000

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
padding = { x = 5, y = 3 }
