[general]
import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[font]
size = 16.0
offset = { x = 1, y = 1 }

[font.normal]
family = "RobotoMono Nerd Font"
style = "Regular"

[bell]
duration = 400
color = "#585b70"

[cursor]
style.blinking = "Never"

[scrolling]
history = 100000

[window]
decorations_theme_variant = "Dark"
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
padding = { x = 5, y = 3 }
