[dotfiles]
"~/.Brewfile" = "brew/.Brewfile"
"~/.claude/statusline.sh" = "claude/statusline.sh"
"~/.config/ghostty" = "ghostty"
"~/.config/git" = "git"
"~/.config/lazygit" = "lazygit"
"~/.config/mise/config.toml" = "mise/config.toml"
"~/.config/nvim" = "nvim"
"~/.config/tmux" = "tmux"
"~/.config/zsh" = "zsh/config"
"~/.hushlogin" = "login/.hushlogin"
"~/.inputrc" = "readline/.inputrc"
"~/.ipython/profile_default/ipython_config.py" = "ipython/ipython_config.py"
"~/.vimrc" = "vim/.vimrc"
"~/.zshenv" = "zsh/.zshenv"
