[tools]
fd = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
neovim = "0.11"
node = "24"
ripgrep = "latest"
tmux = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
"pipx:ipython" = { version = "9", uvx_args = "--with catppuccin" }
