[tools]
fd = "latest"
fzf = "latest"
gh = "latest"
git-lfs = "latest"
lazygit = "latest"
neovim = "0.12"
node = "24"
ripgrep = "latest"
tmux = "latest"
tree-sitter = "latest"
usage = "latest"
uv = "latest"
zoxide = "latest"
"pipx:ipython" = { version = "9", uvx_args = "--with catppuccin" }

[settings]
auto_update = true
