setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY

HISTFILE="$XDG_STATE_HOME"/zsh/history
HISTSIZE=4294967296
HISTTIMEFORMAT='[%F %T] '
SAVEHIST=4294967296
