setopt EXTENDED_HISTORY
setopt HIST_FIND_NO_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY

export HISTFILE="${ZDOTDIR:-$HOME}/.zsh_history"
export HISTSIZE=4294967296
export HISTTIMEFORMAT='[%F %T] '
export SAVEHIST=4294967296
