# Enable mouse control
set -g mouse on

# Set prefix keys
set -g prefix C-a

# Rebind keys to split pane
bind | split-window -h -c "#{pane_current_path}"
bind _ split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

# Bind keys to select pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Bind keys to move between prompts
bind -n M-Up {
    copy-mode
    send-keys -X start-of-line
    send-keys -X search-backward ''
}
bind -n M-Down {
    copy-mode
    send-keys -X end-of-line
    send-keys -X search-forward ''
}

# Reduce escape time, see https://superuser.com/a/252717/65504
set -s escape-time 50

# Sensible defaults
set -g history-limit 10000
set -g display-time 4000
set -g status-interval 5
set -g base-index 1
set -g renumber-windows on

# Send focus events to applications
set -g focus-events on

# Set display terminal
set -g default-terminal "${TERM}"

# Enable CSI u extended key support for applications that request it
set -g extended-keys on
set -g extended-keys-format csi-u
set -as terminal-features 'xterm*:extkeys'

# Set theme
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_text " #{b:pane_current_command}"
set -g @catppuccin_window_current_text " #{b:pane_current_command}"
set -g @catppuccin_status_left_separator '█'

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ''
set -g  status-right "#{E:@catppuccin_status_directory}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -ag status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"

run ~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux

# Override message and command styles to left align
set -gF message-style "#{s/align=[^,]*/align=left/:message-style}"
set -gF message-command-style "#{s/align=[^,]*/align=left/:message-command-style}"

if-shell "command -v pbcopy" "set -s copy-command 'pbcopy'"
if-shell "command -v wl-copy" "set -s copy-command 'wl-copy'"
