import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 1

[bell]
duration = 400
color = "#585B70"

[scrolling]
history = 100000

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 3
