import = ["~/.config/alacritty/catppuccin/catppuccin-latte.toml"]

[bell]
duration = 400

[env]
TERM = "xterm-256color"

[font]
size = 16.0

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[font.offset]
x = 1
y = 1

[scrolling]
history = 100000

[shell]
args = ["zsh", "--login"]
program = "/usr/bin/env"

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"

[window.padding]
x = 5
y = 3
