import = ["~/.config/alacritty/catppuccin/catppuccin-mocha.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 16.0
offset.x = 1
offset.y = 1

[font.normal]
family = "RobotoMono Nerd Font Mono"
style = "Regular"

[bell]
duration = 400
color = "#585B70"

[scrolling]
history = 100000

[window]
option_as_alt = "OnlyLeft"
startup_mode = "Maximized"
padding.x = 5
padding.y = 3
